common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgres://djangouser:testpassword@172.30.19.232/forum
  require_ssl: false # стоит ли шифровать соединение с базой